---
# Directory Structure
base_dir: "/app"
oracle_home: "{{ base_dir }}/oracle"
java_home: "{{ base_dir }}/java"
application_home: "{{ base_dir }}/user_projects/applications"
domain_home: "{{ base_dir }}/user_projects/domains/{{ weblogic_domain }}"
inventory_home: "{{ base_dir }}/oraInsta.loc"

# Security Configuration
machine_user: "weblogic"
weblogic_user: "weblogic"
weblogic_pass: "weblogic1"

# WebLogic Configuration
install_type: "WebLogic Server"
weblogic_domain: "base_domain"

# Server Configuration
admin_server:
  name: "AdminServer"
  address: "192.168.56.10"
  port: 7001

managed_server:
  name: "machine1"
  address: "192.168.56.11"
  port: 8001

nodemanager:
  port: 5556
