Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.ssh.insert_key = false
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end

  config.vm.define "admin_server" do |admin|
    admin.vm.hostname = "weblogic-admin"
    admin.vm.network "private_network", ip: "192.168.56.10", name: "VirtualBox Host-Only Ethernet Adapter"
  end

  config.vm.define "managed_server" do |managed|
    managed.vm.hostname = "weblogic-managed"
    managed.vm.network "private_network", ip: "192.168.56.11", name: "VirtualBox Host-Only Ethernet Adapter"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
    sudo sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
    sudo yum update -y
    sudo yum upgrade -y
    sudo yum install epel-release gcc openssl-devel bzip2-devel libffi-devel zlib-devel wget -y 
    cd /usr/local/src
    sudo wget https://www.python.org/ftp/python/3.9.6/Python-3.9.6.tgz
    sudo tar -xvf Python-3.9.6.tgz
    sudo rm -f Python-3.9.6.tgz
    cd Python-3.9.6
    sudo ./configure --prefix=/usr/local/
    sudo make
    sudo make altinstall
    sudo ln -s /usr/local/bin/python3.9 /usr/local/bin/python3
    echo "$(cat /vagrant/docker_vagrant_key.pub)" >> /home/vagrant/.ssh/authorized_keys
    sudo chmod 600 /home/vagrant/.ssh/authorized_keys
    sudo chown vagrant:vagrant /home/vagrant/.ssh/authorized_keys
  SHELL
end