---
- name: Setup WebLogic Environment
  hosts: weblogic
  become: yes
  roles:
    - setup-weblogic

- name: Configure Certificates
  hosts: weblogic
  become: yes
  roles:
    - { role: manage-cert, tags: ["certificates"] }
