---
- name: "Copy domain template"
  template:
    src: "create_domain.py.j2"
    dest: "{{ base_dir }}/create_domain.py"
    mode: 0755

- name: "Create domain"
  become_user: "{{ machine_user }}"
  command: "{{ oracle_home }}/oracle_common/common/bin/wlst.sh {{ base_dir }}/create_domain.py"

- name: "Pack domain"
  become_user: "{{ machine_user }}"
  command: "{{ oracle_home }}/oracle_common/common/bin/pack.sh -domain={{ domain_home }} -template={{ domain_home }}/{{ weblogic_domain }}.jar -template_name={{ weblogic_domain }} -managed=true"
  args:
    creates: "{{ domain_home }}/{{ weblogic_domain }}.jar"

- name: "Adjust permissions for rsync"
  file:
    path: "{{ domain_home }}/{{ weblogic_domain }}.jar"
    owner: vagrant
    group: vagrant
    mode: "0644"

- name: "Copy to managed_server"
  remote_user: vagrant
  synchronize:
    src: "{{ domain_home }}/{{ weblogic_domain }}.jar"
    dest: "/tmp/"
    mode: pull
  delegate_to: "{{ groups['managed'][0] }}"

- name: "Remove domain template"
  file:
    path: "{{ base_dir }}/create_domain.py"
    state: absent
