---
- name: "Change permissions of base_domain.jar"
  file:
    path: "/tmp/{{ weblogic_domain }}.jar"
    owner: "{{ machine_user }}"
    group: "{{ machine_user }}"
    mode: 0755

- name: "Unpack domain"
  become_user: "{{ machine_user }}"
  command: "{{ oracle_home }}/oracle_common/common/bin/unpack.sh -domain={{ domain_home }} -template=/tmp/{{ weblogic_domain }}.jar"

- name: "Set SecureListener to false in nodemanager.properties"
  lineinfile:
    path: "{{ domain_home }}/nodemanager/nodemanager.properties"
    regexp: "^SecureListener="
    line: "SecureListener=false"
    create: yes

- name: "Start Node Manager"
  become_user: "{{ machine_user }}"
  shell: "nohup {{ domain_home }}/bin/startNodeManager.sh &"

- name: "Ensure security directory exists for Managed Server"
  file:
    path: "{{ domain_home }}/servers/{{ managed_server_name }}/security"
    state: directory
    owner: "{{ machine_user }}"
    group: "{{ machine_user }}"
    mode: 0755

- name: "Create boot.properties for managed server"
  copy:
    dest: "{{ domain_home }}/servers/{{ managed_server_name }}/security/boot.properties"
    content: |
      username={{ weblogic_user }}
      password={{ weblogic_pass }}
    owner: "{{ machine_user }}"
    group: "{{ machine_user }}"
    mode: 0600

- name: "Start managed Server"
  become_user: "{{ machine_user }}"
  shell: "nohup {{ domain_home }}/bin/startManagedWebLogic.sh {{ managed_server_name }} http://{{ admin_server_address }}:{{ admin_server_port }} &"
