---
- name: "Copy domain template"
  template:
    src: "create_domain.py.j2"
    dest: "{{ app_home }}/create_domain.py"
    mode: 0755

- name: "Create domain"
  become_user: "{{ machine_user }}"
  shell: "{{ oracle_home }}/oracle_common/common/bin/wlst.sh {{ app_home }}/create_domain.py"

- name: "Start weblogic admin"
  become_user: "{{ machine_user }}"
  shell: "nohup {{ domain_home }}/startWebLogic.sh &"

- name: "Check admin status"
  wait_for:
    host: "{{ ansible_facts.eth1.ipv4.address }}"
    port: "{{ admin_server_port }}"
    state: started
    delay: 10
    timeout: 120

- name: "Pack domain"
  become_user: "{{ machine_user }}"
  shell: "{{ oracle_home }}/oracle_common/common/bin/pack.sh -domain={{ domain_home }} -template={{ domain_home }}/{{ weblogic_domain }}.jar -template_name={{ weblogic_domain }} -managed=true"
  args:
    creates: "{{ domain_home }}/{{ weblogic_domain }}.jar"

- name: "Adjust permissions for rsync"
  file:
    path: "{{ domain_home }}/{{ weblogic_domain }}.jar"
    owner: vagrant
    group: vagrant
    mode: "0644"

- name: "Copy to managed_server"
  remote_user: vagrant
  synchronize:
    src: "{{ domain_home }}/{{ weblogic_domain }}.jar"
    dest: "/tmp/"
    mode: pull
  delegate_to: "{{ groups['managed'][0] }}"
