- name: "Pre-installation checks"
  block:
    - name: "Check if WebLogic is already installed"
      stat:
        path: "{{ oracle_home }}/wlserver"
      register: wls_install

    - name: "Check available disk space"
      shell: "df -h / | awk 'NR==2 {print $4}'"
      register: available_space
      changed_when: false
  tags: ["precheck"]

- name: "Create group"
  group:
    name: "{{ machine_user }}"

- name: "Create user"
  user:
    name: "{{ machine_user }}"
    group: "{{ machine_user }}"

- name: "Create required directories"
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ machine_user }}"
    group: "{{ machine_user }}"
    mode: "0755"
  with_items:
    - "{{ oracle_home }}"
    - "{{ domain_home }}"
    - "{{ application_home }}"
  tags: ["setup"]

- name: "Changing /app ownership and permissions"
  file:
    path: /app
    owner: "{{ machine_user }}"
    group: "{{ machine_user }}"
    mode: 0755
    recurse: yes

- name: "Install java"
  become_user: "{{ machine_user }}"
  unarchive:
    src: "{{ item }}"
    dest: "/app"
  with_items:
    - "jdk-8u421-linux-x64.tar.gz"

- name: "Link java_home"
  file:
    src: "/app/jdk1.8.0_421"
    dest: "{{ java_home }}"
    owner: "{{ machine_user }}"
    group: "{{ machine_user }}"
    state: link
    force: yes

- name: "Extract weblogic file"
  become_user: "{{ machine_user }}"
  unarchive:
    src: "{{ item }}"
    dest: "{{ base_dir }}"
  with_items:
    - "fmw_14.1.1.0.0_wls_lite_Disk1_1of1.zip"

- name: "Set oraInsta.loc in oracle_home"
  become_user: "{{ machine_user }}"
  template:
    src: "oraInsta.loc.j2"
    dest: "{{ base_dir }}/oraInsta.loc"
    mode: 0755

- name: "Response file to silent installation"
  become_user: "{{ machine_user }}"
  template:
    src: "wls.rsp.j2"
    dest: "{{ base_dir }}/wls.rsp"
    mode: 0755

- name: "Install weblogic silent mode"
  become_user: "{{ machine_user }}"
  command: "{{ java_home }}/bin/java -Xmx1024m -jar {{ base_dir }}/fmw_14.1.1.0.0_wls_lite_generic.jar -silent -responseFile {{ base_dir }}/wls.rsp -invPtrLoc {{ inventory_home }}/"

- name: "Remove installation files"
  become_user: "{{ machine_user }}"
  file:
    path: "{{ base_dir }}/{{ item }}"
    state: absent
  with_items:
    - "fmw_14.1.1.0.0_wls_lite_generic.jar"
    - "wls.rsp"

- name: "Verify installation"
  block:
    - name: "Check WebLogic version"
      command: "{{ oracle_home }}/oracle_common/common/bin/wlst.sh -c 'print preferencesMBean.getWeblogicVersion()'"
      register: wls_version
      changed_when: false

    - name: "Verify Java version"
      command: "{{ java_home }}/bin/java -version"
      register: java_version
      changed_when: false
  tags: ["verify"]
