- name: "Create group"
  group:
    name: "{{ machine_user }}"

- name: "Create user"
  user:
    name: "{{ machine_user }}"
    group: "{{ machine_user }}"

- name: "Create Oracle Home"
  file:
    path: "{{ oracle_home }}"
    state: directory
    owner: "{{ machine_user }}"
    group: "{{ machine_user }}"
    mode: "0755"

- name: "Create Domain Home"
  file:
    path: "{{ domain_home }}"
    state: directory
    owner: "{{ machine_user }}"
    group: "{{ machine_user }}"
    mode: "0755"

- name: "Create Application Home"
  file:
    path: "{{ application_home }}"
    state: directory
    owner: "{{ machine_user }}"
    group: "{{ machine_user }}"
    mode: "0755"

- name: "Changing /app ownership and permissions"
  file:
    path: /app
    owner: "{{ machine_user }}"
    group: "{{ machine_user }}"
    mode: 0755
    recurse: yes

- name: "Install java"
  become_user: "{{ machine_user }}"
  unarchive:
    src: "{{ item }}"
    dest: "/app"
  with_items:
    - "jdk-8u421-linux-x64.tar.gz"

- name: "Link java_home"
  file:
    src: "/app/jdk1.8.0_421"
    dest: "{{ java_home }}"
    owner: "{{ machine_user }}"
    group: "{{ machine_user }}"
    state: link
    force: yes

- name: "Extract weblogic file"
  become_user: "{{ machine_user }}"
  unarchive:
    src: "{{ item }}"
    dest: "{{ app_home }}"
  with_items:
    - "fmw_14.1.1.0.0_wls_lite_Disk1_1of1.zip"

- name: "Set oraInsta.loc in oracle_home"
  become_user: "{{ machine_user }}"
  template:
    src: "oraInsta.loc.j2"
    dest: "{{ app_home }}/oraInsta.loc"
    mode: 0755

- name: "Response file to silent installation"
  become_user: "{{ machine_user }}"
  template:
    src: "wls.rsp.j2"
    dest: "{{ app_home }}/wls.rsp"
    mode: 0755

- name: "Install weblogic silent mode"
  become_user: "{{ machine_user }}"
  shell: "{{ java_home }}/bin/java -Xmx1024m -jar {{ app_home }}/fmw_14.1.1.0.0_wls_lite_generic.jar -silent -responseFile {{ app_home }}/wls.rsp -invPtrLoc {{ inventory_home }}/"
