name: Setup docker

on:
  workflow_dispatch:

jobs:
  setup_docker:
    name: Create docker container
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.9.0

      - name: Build docker image
        run: docker build ./infrastructure/Dockerfile --tag ansible-control:latest
